### ISSUE TITLE
Missing dependency @daybrush/utils

### ISSUE THREAD

**Issue by s33h0w** [daybrush/dragscroll#1]
Hi, is the dependency `@daybrush/utils` missing here?

[src/DragScroll.ts](https://github.com/daybrush/dragscroll/blob/master/src/DragScroll.ts#L2)
![image](https://user-images.githubusercontent.com/27037621/106842993-fa6b2c80-66df-11eb-93f9-ff7bffa79692.png)

[package.json](https://github.com/daybrush/dragscroll/blob/master/package.json)
![image](https://user-images.githubusercontent.com/27037621/106843075-271f4400-66e0-11eb-8737-1dcc63f563a5.png)

**Comment by daybrush** [comment]
@s33h0w 

Thank you :) 1.0.3 is released.
